### PR TITLE
Add example usage with telethon

### PR DESCRIPTION
**Pull request by gokulsoumya**
[Telethon](https://github.com/LonamiWebs/Telethon) uses the MTProto protocol directly and hence the usage is different. This example showcases how to achieve the simple calendar example in telethon.

### CODE REVIEW

**Comment by gokulsoumya** [comment]
Another approach that's much cleaner is to subclass `DetailedTelegramCalendar` and override the methods so that the final differences in usage are minimal:

```python
class TelethonCalendar(DetailedTelegramCalendar):
    def _build(self, step=None, **kwargs):
        super()._build(step=step)
        button_markup_data: Dict = json.loads(self._keyboard)

        buttons: List[List[Button]] = []
        for button_row in button_markup_data["inline_keyboard"]:
            button_row: List[Dict]
            buttons.append(
                [
                    Button.inline(text=str(but["text"]), data=but["callback_data"])
                    for but in button_row
                ]
            )

        self._keyboard = buttons

    @staticmethod
    def func(calendar_id=0) -> Callable:
        def inner(callback_data: bytes) -> bool:
            start = telegram_bot_calendar.base.CB_CALENDAR + "_" + str(calendar_id)
            return callback_data.decode("utf-8").startswith(start)

        return inner

...

@bot.on(events.NewMessage(pattern="/start"))
async def start(event):
    calendar, step = TelethonCalendar().build()
    await event.respond(f"Select {LSTEP[step]}", buttons=calendar)


@bot.on(events.CallbackQuery(pattern=TelethonCalendar.func()))
async def cal(event):
    result, key, step = TelethonCalendar().process(event.data.decode("utf-8"))

    if not result and key:
        await event.edit(f"Select {LSTEP[step]}", buttons=key)
    elif result:
        await event.edit(f"You selected {result}")
```

**Comment by artembakhanov** [comment]
That is nice, thank you very much. Now I am considering adding support of the telethon buttons inside the library but the problem is with requirements. I do not want the package to have an extra requirement to be installed just because of that. 
The example itself is great but now I am thinking if I can make it easier and the same for all the libraries. 
If you have any ideas text here or on telegram @artembakhanov.

**Comment by artembakhanov** [comment]
I think the best way is to add extra_require to the package. Also, a telethon flag was added to the base class. Now it is supported. Please let me know if it is ok for you. Thanks

**Review by artembakhanov — APPROVED** [review]

**Comment by gokulsoumya** [comment]
Thanks for adding support for Telethon right into the library. `extra_require` does seem to be the best way to do it. Thanks again for you work in this library :)

**Review by artembakhanov — APPROVED** [review]

**Pull request merged**
